<?php
class Valibus_Fbreward_GenerateController extends Mage_Core_Controller_Front_Action{

    public function v1Action(){
        try {

            /** @var $rule Mage_SalesRule_Model_Rule */
            $rule=Mage::getModel('salesrule/rule');
            $rule->load(Valibus_Fbreward_Helper_Data::FBREWARD_SHAREPAGE_RULE_ID);
            /** @var $generator Mage_SalesRule_Model_Coupon_Massgenerator */
            $generator=$rule->getCouponMassGenerator();
            $parameters = array(
                'qty'=>1,
                'rule_id'=>Valibus_Fbreward_Helper_Data::FBREWARD_SHAREPAGE_RULE_ID,
                'format'=>Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC,
                'type'=>Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED,
                'dash_every_x_characters'=>0,
                'prefix'=>'FqsdBf',
                'suffix'=>'',
                'length'=>8
            );
            $generator->setData($parameters);
            $generator->generatePool();
            $generated = $generator->getGeneratedCount();
            /*Mage::getSingleton('checkout/session')->addSuccess(
                $this->__('Coupon code "%s" was generated.', Mage::helper('valibus_fbreward')->getGeneratedCouponLabel())
            );*/
            //$this->_goBack();
        } catch (Exception $e) {
            echo 'Exception recue : ',  $e->getMessage(), "\n";
        }
        $this->loadLayout();
        $this->renderLayout();
    }
    protected function _goBack()
    {
        $returnUrl = $this->getRequest()->getParam('return_url');
        if ($returnUrl) {

            if (!$this->_isUrlInternal($returnUrl)) {
                throw new Mage_Exception('External urls redirect to "' . $returnUrl . '" denied!');
            }
            $this->getResponse()->setRedirect($returnUrl);
        } elseif (!Mage::getStoreConfig('checkout/cart/redirect_to_cart')
            && !$this->getRequest()->getParam('in_cart')
            && $backUrl = $this->_getRefererUrl()
        ) {
            $this->getResponse()->setRedirect($backUrl);
        } else {
            if (($this->getRequest()->getActionName() == 'add') && !$this->getRequest()->getParam('in_cart')) {
                $this->_getSession()->setContinueShoppingUrl($this->_getRefererUrl());
            }
            $this->_redirect('checkout/cart');
        }
        return $this;
    }
}