<meta property="fb:app_id" content="<?php echo $appId; ?>"/>
<meta property="og:title" content="POC Facebook API"/>
<meta property="og:type" content="blog"/>
<meta property="og:site_name" content="Valib.us Blog"/>
<meta property="og:url" content="<?php echo $urlPage; ?>"/>
<meta property="og:image" content="http://www.valib.us/skin/frontend/valibus/custom/images/valibus.png" />
<meta property="og:description" content="ceci est un poc de test" />